# Linear Algebra

* misconception that Linear algebra is algebra and that is all about plotting line with $y = mx + b $

* this is why it should be referred to as `Vector Algebra` or `Matrix Algebra` as it is much more to do with than just plotting lines

  * much more useful is many metaphysical ways

* concerns itself with linear systems but represents them with `vectors` and `matrices` 

* inevitable to learn Linear Algebra in ML and Data Science to see what is going on inside the black box

## What is a Vector?

* imagine vector as arrow in the space with specific length and direction, its tail sits at (0, 0) of Cartesian plane

  * vector usually represents data

  * usually represents as $ \bar{v} = \begin{bmatrix}x \\ y \end{bmatrix} $

  * example, 

    * $\bar{v} = \begin{bmatrix} 3 \\ 2 \end{bmatrix}$

      * think of this as 3 to the right and 2 to the top

        * ![](img/01.linear_algebra-2604064652.png)
  
    * house with 18000 square feet and $260000 price can be represented as

      * $\bar{v} = \begin{bmatrix} 18000 \\ 260000 \end{bmatrix}$

* use NumPy array or SciPy to represent and perform operations on vector rather than Python list

  * for computational efficiency

In [1]:
import numpy as np

np.array([3, 2])

array([3, 2])

* vector

  * in physics

    * direction and magnitude

  * in math

    * direction and scale on XY plane

  * in computer science

    * way of storing list of numbers

* computer science view is the one that will be used for DS and ML

* without visual representation of what a vector is

  * it is impossible to grasp may fundamental concepts like `linear dependence`, `determinant`, etc...

  ![](img/01.linear_algebra-2604065818.png)


* where is it used

  * computer graphics (animations and transformations)

  * linear programming (linear algebra is used to maximise/minimise the solutions within the given constraints)

  * physical and physics related simulations

  * used is so many areas so it is hard to see the generalisation

* dimension

  * vector can be on n dimension, but it is hard to visualise beyond 3d


### Adding and Combining Vectors

* moving tail of one to the tip of another and walking to end of the tip

![](img/01.linear_algebra-2604072254.png)

![](img/01.linear_algebra-2704060019.png)

* numerically just adding corresponding elements

* vector addition is `commutative`

  * $ \bar{a} + \bar{b} = \bar{b} + \bar{a} $


### Scaling Vectors

* scaling is growing or shrinking the length of the vector by the scaling factor called `scalar` 

* mathematically, multiple each element with the scalar 

![](img/01.linear_algebra-2704060756.png)

* scaling does not change the direction, just the magnitude

  * negative number flips the direction

  * but it still stays in the same line (linearly dependent)

  ![](img/01.linear_algebra-2704061859.png)

### Span and Linear Dependence

* with linear combination (scaling and adding two vectors together) we can reach unlimited number of vectors

  * this is called the `span` of those two vectors

  * span will be unlimited if the vectors are pointing in different directions (not in same line)

    * linear independence

  * span will be limited if they are in the same line

    * linear dependence

    * for 3 or more dimensions, the span would be limited to a plane in the lower dimension

* `determinant` helps to find if a vectors are linearly independent or not

* it is useful to know because solving system of linear equations becomes difficult or unsolvable if they are linearly dependent


## Linear Transformation

* use vector to transform another vector in a function-like manner

### Basis Vectors

* $\hat{i}, \hat{j}$ are basis vectors used to describe transformations on other vectors

* usually perpendicular to each other in positive direction with length 1

![](img/01.linear_algebra-2704070230.png)

* basis to build or form any vector (using linearly independence and span)

* matrix is collection of vectors with `n` rows and `m` columns, it convenient way to package data

* basis vector can be combined into matrix form

  * $\hat{i} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$

  * $\hat{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$

  * $basis = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

![](img/01.linear_algebra-2704071044.png)

* linear transformation

  * stretch, squish, sheer or rotate vector by tracking its basis vector movements

  ![](img/01.linear_algebra-2704071348.png)

* with linear transformation, we can achieve

  * scale

  * rotation

  * sheer

  * inversion

  ![](img/01.linear_algebra-2704071641.png)

* we cannot have transformation that results in curvy or squiggly, hence `linear algebra`

### Matrix Vector Multiplication

* tracking where $\hat{i}$ and $\hat{j}$ lands after transformation helps to see where a new vector lands

* $\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

* $\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} = \begin{bmatrix} x.a + y.b \\ x.c + y.d \end{bmatrix}$

* this formula may seem confusing but it is a packed notation of scaling basis vectors and adding them together

* $\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} = x.\begin{bmatrix} a \\ c\end{bmatrix} y.\begin{bmatrix} b \\ d\end{bmatrix}$

* matrix is just a packed notation of basis vectors $\hat{i}, \hat{j}$

* in NumPy we use `dot` method of an array to perform matrix vector multiplication

* in NumPy each inner array represents row vector, so when composing matrix from $\hat{i}, $\hat{j}$, the matrix need to be transposed 


In [1]:
import numpy as np

basis = np.array(
    [[3, 0],
     [0, 3]]
)

v = np.array([1, 1])

basis.dot(v)


array([3, 3])

In [2]:
import numpy as np

# Declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])

# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = np.array([i_hat, j_hat]).transpose()

# declare vector v
v = np.array([1,1])

# create new vector
# by transforming v with dot product
basis.dot(v)

array([2, 3])

* the transformation works the same way for 3 or more dimensions as well

* some transformation can shift vector space into fewer or more dimensions (this is what a non-square matrix will do)

## Matrix Multiplication

* matrix multiplication - applying multiple transformations to vector

* $\begin{bmatrix}a & b \\ c & d \end{bmatrix}\begin{bmatrix}e & f \\ g & h \end{bmatrix} = \begin{bmatrix}ae + bg & af + bh \\ ce + dy & cf+dh \end{bmatrix}$

* memory trick - `over and down`

* `matmul` in numpy is used for matrix multiplication

  * `@` shorthand

* order of transformation matters

  * matrix product is NOT commutative (i.e. cannot flip orders)

  * always apply inner most to outer most

In [4]:
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine Transformations
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))
v = array([1, 2])
print(combined.dot(v)) # [-1, 1]

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


## Determinants

* tells how much a vector space changes in scale with linear transformation

  * the factor by which it changes is called `determinant`

  * i.e it tells how much vector space is stretched or squished

  ![](img/01.linear_algebra-0405063950.png)

* factor of 6 means - vector space scaled up by 6 times

* factor of 1 means - no scaling to vector space

  * rotating and shearing will have determinant of 1

  ![](img/01.linear_algebra-0405064225.png)

* when orientation is flipped ($\hat{i}, \hat{j}$, changes position clockwise) 

  * the determinant will be negative

  ![](img/01.linear_algebra-0405064455.png)

* if determinant is 0, then it means we have `linearly dependent` vectors

  * vector space is squished into lesser dimensions by the transformation

  * this means we have harder problem at hand to solve

  ![](img/01.linear_algebra-0405064724.png)

In [5]:
from numpy.linalg import det
from numpy import array

# Calculate determinant
i_hat = array([3, 0])
j_hat = array([0, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 6.0

# Determinant for Shear
i_hat = array([1, 0])
j_hat = array([1, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 1.0

# Negative determinant
i_hat = array([-2, 1])
j_hat = array([1, 2])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints -5.0

# Zero determinant
i_hat = array([-2, 1])
j_hat = array([3, -1.5])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant) # prints 0.0

6.0
1.0
-5.000000000000001
0.0


## Special Types of Matrices

### Square Matrix

* equal number of rows and columns

* $A = \begin{bmatrix} 4 & 2 & 7 \\ 5 & 1 & 9 \\ 4 & 0 & 1 \end{bmatrix}$

* mainly used to represent linear transformations

* requirement for many operations like `eigendecomposition`

### Identity Matrix

* square matrix with 1s along the leading diagonal and 0s in other places

* $I = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

* when applied to another matrix, it leaves the original matrix

  * useful when reversing a transformation

### Inverse Matrix

* undo the matrix transformation

* inverse of $A$ is represented using $A^{-1}$

* $ A = \begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix}$

* $ A^{-1} = \begin{bmatrix} -\frac{1}{2} & 0 & \frac{1}{3} \\ 5.5 & -2 & \frac{4}{3} \\ -2 & 1 & \frac{1}{3} \end{bmatrix}$

* $A A^{-1} = A^{-1} A = I$

### Diagonal Matrix

* non zero in leading diagonal and zeros in other places

* $D = \begin{bmatrix} 4 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 5 \end{bmatrix}$

* desirable in certain computation as it represents simple scaler applied to vector space

### Triangular Matrix

* non-zero value in leading diagonal and above (upper triangle) or below (lower triangle)

* $ U = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$

* $ L = \begin{bmatrix} 1 & 0 & 0 \\ 2 & 3 & 0 \\ 4 & 5 & 6 \end{bmatrix}$

* used in numerical analysis as these are typically easier to solve

* show up in decompositions like LU decompositions

### Sparse Matrix

* matrix with mostly zero and few non-zero values

* not very interesting from pure mathematical point of view

* but provides efficiency opportunity from computing point of view

  * when storing we only need to track where non-zero values are ignoring zeros

* $\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$